/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9Hj4GR0Kp70
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"

export function prodoc() {
  return (
    <div className="flex flex-col items-center justify-center space-y-4">
      <Avatar className="h-24 w-24 border-2 border-gray-200 rounded-full">
        <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
        <AvatarFallback>JP</AvatarFallback>
      </Avatar>
      <h1 className="text-3xl font-bold">Dr. John Doe</h1>
      <p className="text-gray-500 dark:text-gray-400">Cardiologist</p>
      <div className="w-full max-w-md">
        <Card>
          <CardHeader>
            <CardTitle>Profile</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4">
            <div className="space-y-2">
              <Label htmlFor="experience">Experience</Label>
              <p id="experience">10 years</p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="education">Education</Label>
              <p id="education">Harvard Medical School</p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="affiliations">Professional Affiliations</Label>
              <p id="affiliations">American Heart Association</p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="bio">Bio</Label>
              <p id="bio">
                Dr. John Doe is a cardiologist with 10 years of experience. He received his medical degree from Harvard
                Medical School and is affiliated with multiple hospitals and medical centers.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
